Update .appveyor.yml
Hot fix : Windows binary raise an exception regarding missing json module from filter plugin 

 File "cutevariant\gui\plugin.py", line 338, in find_plugins
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "O:\sacha\software\cutevariant-win32-latest\cutevariant\cutevariant\gui\p
lugins\filters_editor\widgets.py", line 3, in <module>
  File "C:\Users\015461~1.CHU\AppData\Local\Temp\embedded.3px_9oev.zip\shibokens
upport\__feature__.py", line 146, in _import
ModuleNotFoundError: No module named 'json'
[6096] Failed to execute script __main__